INSERT INTO bucket_test_type(created_at, updated_at, description, phrases, test_type) VALUES(now(), now(), "완전 현직 개발자 type", "나에게 딱 맞는\n개발자 직군을 찾아보세요", 'TYPE_COMMON_1');
INSERT INTO bucket_test_type(created_at, updated_at, description, phrases, test_type) VALUES(now(), now(), "개발자 준비 중 취업러 type", "지금 백엔드와 프론트엔드\n갈림길에 있나요?", 'TYPE_COMMON_2');
INSERT INTO bucket_test_type(created_at, updated_at, description, phrases, test_type) VALUES(now(), now(), "기업 성향을 알아보고 싶은 type", "나는 스타트업 성향일까\n대기업 성향일까?", 'TYPE_COMMON_3');
INSERT INTO bucket_test_type(created_at, updated_at, description, phrases, test_type) VALUES(now(), now(), "성향 테스트를 좋아하는 사람 type", "나도 개발자가 된다면?\n코딩지식없이 테스트하기!", 'TYPE_COMMON_4');
INSERT INTO bucket_test_type(created_at, updated_at, description, phrases, test_type) VALUES(now(), now(), "아이들은 위한 엄마들의 맘카페 type", "우리 아이의 코딩 잠재력을\n바로 확인하세요!", 'TYPE_MOM_CAFE_1');

INSERT INTO bias(pillar, bias, en_bias, kr_bias) VALUES
('ROLE', 'V', 'Visualization', '시각화'),
('ROLE', 'A', 'Architecture', '설계'),
('SCALE', 'S', 'Startup', '스타트업'),
('SCALE', 'C', 'Corporation', '대기업'),
('INTEREST', 'P', 'Product', '상품'),
('INTEREST', 'T', 'Technology', '기술'),
('PRIORITY', 'W', 'Work', '업무'),
('PRIORITY', 'L', 'Life', '개인시간'),
('REFERENCE', 'J', 'ETC', '기타'),
('REFERENCE', 'Y', 'ETC', '기타');


INSERT INTO question (created_at, updated_at, pillar, title, answer_type) VALUES
(now(), now(), 'ROLE', 'Visualization vs Architecture', 'PRESET'),
(now(), now(), 'ROLE', 'Visualization vs Architecture', 'PRESET'),
(now(), now(), 'ROLE', 'Visualization vs Architecture', 'PRESET'),
(now(), now(), 'ROLE', 'Visualization vs Architecture', 'PRESET'),
(now(), now(), 'ROLE', 'Visualization vs Architecture', 'PRESET'),
(now(), now(), 'SCALE', 'Startup vs Corporation', 'PRESET'),
(now(), now(), 'SCALE', 'Startup vs Corporation', 'PRESET'),
(now(), now(), 'SCALE', 'Startup vs Corporation', 'PRESET'),
(now(), now(), 'SCALE', 'Startup vs Corporation', 'PRESET'),
(now(), now(), 'SCALE', 'Startup vs Corporation', 'PRESET'),
(now(), now(), 'INTEREST', 'Product vs Technology', 'PRESET'),
(now(), now(), 'INTEREST', 'Product vs Technology', 'PRESET'),
(now(), now(), 'INTEREST', 'Product vs Technology', 'PRESET'),
(now(), now(), 'INTEREST', 'Product vs Technology', 'PRESET'),
(now(), now(), 'INTEREST', 'Product vs Technology', 'PRESET'),
(now(), now(), 'PRIORITY', 'Work vs Life', 'PRESET'),
(now(), now(), 'PRIORITY', 'Work vs Life', 'PRESET'),
(now(), now(), 'PRIORITY', 'Work vs Life', 'PRESET'),
(now(), now(), 'PRIORITY', 'Work vs Life', 'PRESET'),
(now(), now(), 'PRIORITY', 'Work vs Life', 'PRESET'),
(now(), now(), 'ROLE', 'Visualization vs Architecture', 'GAGE'),
(now(), now(), 'ROLE', 'Visualization vs Architecture', 'GAGE'),
(now(), now(), 'ROLE', 'Visualization vs Architecture', 'GAGE'),
(now(), now(), 'ROLE', 'Visualization vs Architecture', 'GAGE'),
(now(), now(), 'ROLE', 'Visualization vs Architecture', 'GAGE'),
(now(), now(), 'SCALE', 'Startup vs Corporation', 'GAGE'),
(now(), now(), 'SCALE', 'Startup vs Corporation', 'GAGE'),
(now(), now(), 'SCALE', 'Startup vs Corporation', 'GAGE'),
(now(), now(), 'SCALE', 'Startup vs Corporation', 'GAGE'),
(now(), now(), 'SCALE', 'Startup vs Corporation', 'GAGE'),
(now(), now(), 'INTEREST', 'Product vs Technology', 'GAGE'),
(now(), now(), 'INTEREST', 'Product vs Technology', 'GAGE'),
(now(), now(), 'INTEREST', 'Product vs Technology', 'GAGE'),
(now(), now(), 'INTEREST', 'Product vs Technology', 'GAGE'),
(now(), now(), 'INTEREST', 'Product vs Technology', 'GAGE'),
(now(), now(), 'PRIORITY', 'Work vs Life', 'GAGE'),
(now(), now(), 'PRIORITY', 'Work vs Life', 'GAGE'),
(now(), now(), 'PRIORITY', 'Work vs Life', 'GAGE'),
(now(), now(), 'PRIORITY', 'Work vs Life', 'GAGE'),
(now(), now(), 'PRIORITY', 'Work vs Life', 'GAGE'),
(now(), now(), 'REFERENCE', '현재 해당 직무에서 근무하신 기간이 어떻게 되나요?', 'INFO'),
(now(), now(), 'REFERENCE', '향후 희망하는 직무가 무엇이에요?', 'INFO');

INSERT INTO preset (created_at, updated_at, question_id, sequence, label, bias, weight) VALUES
(now(), now(), 1, 0, 'VVVVVV', 'V', 1),
(now(), now(), 1, 1, 'AAAAAA', 'A', 1),
(now(), now(), 2, 0, 'VVVVVV', 'V', 1),
(now(), now(), 2, 1, 'AAAAAA', 'A', 1),
(now(), now(), 3, 0, 'VVVVVV', 'V', 1),
(now(), now(), 3, 1, 'AAAAAA', 'A', 1),
(now(), now(), 4, 0, 'VVVVVV', 'V', 1),
(now(), now(), 4, 1, 'AAAAAA', 'A', 1),
(now(), now(), 5, 0, 'VVVVVV', 'V', 1),
(now(), now(), 5, 1, 'AAAAAA', 'A', 1),
(now(), now(), 6, 0, 'SSSSSS', 'S', 1),
(now(), now(), 6, 1, 'CCCCCC', 'C', 1),
(now(), now(), 7, 0, 'SSSSSS', 'S', 1),
(now(), now(), 7, 1, 'CCCCCC', 'C', 1),
(now(), now(), 8, 0, 'SSSSSS', 'S', 1),
(now(), now(), 8, 1, 'CCCCCC', 'C', 1),
(now(), now(), 9, 0, 'SSSSSS', 'S', 1),
(now(), now(), 9, 1, 'CCCCCC', 'C', 1),
(now(), now(), 10, 0, 'SSSSSS', 'S', 1),
(now(), now(), 10, 1, 'CCCCCC', 'C', 1),
(now(), now(), 11, 0, 'PPPPPP', 'P', 1),
(now(), now(), 11, 1, 'TTTTTT', 'T', 1),
(now(), now(), 12, 0, 'PPPPPP', 'P', 1),
(now(), now(), 12, 1, 'TTTTTT', 'T', 1),
(now(), now(), 13, 0, 'PPPPPP', 'P', 1),
(now(), now(), 13, 1, 'TTTTTT', 'T', 1),
(now(), now(), 14, 0, 'PPPPPP', 'P', 1),
(now(), now(), 14, 1, 'TTTTTT', 'T', 1),
(now(), now(), 15, 0, 'PPPPPP', 'P', 1),
(now(), now(), 15, 1, 'TTTTTT', 'T', 1),
(now(), now(), 16, 0, 'WWWWWW', 'W', 1),
(now(), now(), 16, 1, 'LLLLLL', 'L', 1),
(now(), now(), 17, 0, 'WWWWWW', 'W', 1),
(now(), now(), 17, 1, 'LLLLLL', 'L', 1),
(now(), now(), 18, 0, 'WWWWWW', 'W', 1),
(now(), now(), 18, 1, 'LLLLLL', 'L', 1),
(now(), now(), 19, 0, 'WWWWWW', 'W', 1),
(now(), now(), 19, 1, 'LLLLLL', 'L', 1),
(now(), now(), 20, 0, 'WWWWWW', 'W', 1),
(now(), now(), 20, 1, 'LLLLLL', 'L', 1),
(now(), now(), 21, 0, '', 'V', 1),
(now(), now(), 21, 1, '', 'V', 0.5),
(now(), now(), 21, 2, '', 'V', 0),
(now(), now(), 21, 3, '', 'A', 0.5),
(now(), now(), 21, 4, '', 'A', 1),
(now(), now(), 22, 0, '', 'V', 1),
(now(), now(), 22, 1, '', 'V', 0.5),
(now(), now(), 22, 2, '', 'A', 0),
(now(), now(), 22, 3, '', 'A', 0.5),
(now(), now(), 22, 4, '', 'A', 1),
(now(), now(), 23, 0, '', 'V', 1),
(now(), now(), 23, 1, '', 'V', 0.5),
(now(), now(), 23, 2, '', 'V', 0),
(now(), now(), 23, 3, '', 'A', 0.5),
(now(), now(), 23, 4, '', 'A', 1),
(now(), now(), 24, 0, '', 'V', 1),
(now(), now(), 24, 1, '', 'V', 0.5),
(now(), now(), 24, 2, '', 'V', 0),
(now(), now(), 24, 3, '', 'A', 0.5),
(now(), now(), 24, 4, '', 'A', 1),
(now(), now(), 25, 0, '', 'V', 1),
(now(), now(), 25, 1, '', 'V', 0.5),
(now(), now(), 25, 2, '', 'V', 0),
(now(), now(), 25, 3, '', 'A', 0.5),
(now(), now(), 25, 4, '', 'A', 1),
(now(), now(), 26, 0, '', 'S', 1),
(now(), now(), 26, 1, '', 'S', 0.5),
(now(), now(), 26, 2, '', 'C', 0),
(now(), now(), 26, 3, '', 'C', 0.5),
(now(), now(), 26, 4, '', 'C', 1),
(now(), now(), 27, 0, '', 'S', 1),
(now(), now(), 27, 1, '', 'S', 0.5),
(now(), now(), 27, 2, '', 'S', 0),
(now(), now(), 27, 3, '', 'C', 0.5),
(now(), now(), 27, 4, '', 'C', 1),
(now(), now(), 28, 0, '', 'S', 1),
(now(), now(), 28, 1, '', 'S', 0.5),
(now(), now(), 28, 2, '', 'S', 0),
(now(), now(), 28, 3, '', 'C', 0),
(now(), now(), 28, 4, '', 'C', 0.5),
(now(), now(), 28, 5, '', 'C', 1),
(now(), now(), 29, 0, '', 'S', 1),
(now(), now(), 29, 1, '', 'S', 0.5),
(now(), now(), 29, 2, '', 'S', 0),
(now(), now(), 29, 3, '', 'C', 0.5),
(now(), now(), 29, 4, '', 'C', 1),
(now(), now(), 30, 0, '', 'S', 1),
(now(), now(), 30, 1, '', 'S', 0.5),
(now(), now(), 30, 2, '', 'S', 0),
(now(), now(), 30, 3, '', 'C', 0.5),
(now(), now(), 30, 4, '', 'C', 1),
(now(), now(), 31, 0, '', 'P', 1),
(now(), now(), 31, 1, '', 'P', 0.5),
(now(), now(), 31, 2, '', 'P', 0),
(now(), now(), 31, 3, '', 'T', 0.5),
(now(), now(), 31, 4, '', 'T', 1),
(now(), now(), 32, 0, '', 'P', 1),
(now(), now(), 32, 1, '', 'P', 0.5),
(now(), now(), 32, 2, '', 'P', 0),
(now(), now(), 32, 3, '', 'T', 0.5),
(now(), now(), 32, 4, '', 'T', 1),
(now(), now(), 33, 0, '', 'P', 1),
(now(), now(), 33, 1, '', 'P', 0.5),
(now(), now(), 33, 2, '', 'P', 0),
(now(), now(), 33, 3, '', 'T', 0.5),
(now(), now(), 33, 4, '', 'T', 1),
(now(), now(), 34, 0, '', 'P', 1),
(now(), now(), 34, 1, '', 'P', 0.5),
(now(), now(), 34, 2, '', 'P', 0),
(now(), now(), 34, 3, '', 'T', 0.5),
(now(), now(), 34, 4, '', 'T', 1),
(now(), now(), 35, 0, '', 'P', 1),
(now(), now(), 35, 1, '', 'P', 0.5),
(now(), now(), 35, 2, '', 'P', 0),
(now(), now(), 35, 3, '', 'T', 0.5),
(now(), now(), 35, 4, '', 'T', 1),
(now(), now(), 36, 0, '', 'W', 1),
(now(), now(), 36, 1, '', 'W', 0.5),
(now(), now(), 36, 2, '', 'W', 0),
(now(), now(), 36, 3, '', 'L', 0.5),
(now(), now(), 36, 4, '', 'L', 1),
(now(), now(), 37, 0, '', 'W', 1),
(now(), now(), 37, 1, '', 'W', 0.5),
(now(), now(), 37, 2, '', 'W', 0),
(now(), now(), 37, 3, '', 'L', 0.5),
(now(), now(), 37, 4, '', 'L', 1),
(now(), now(), 38, 0, '', 'W', 1),
(now(), now(), 38, 1, '', 'W', 0.5),
(now(), now(), 38, 2, '', 'W', 0),
(now(), now(), 38, 3, '', 'L', 0.5),
(now(), now(), 38, 4, '', 'L', 1),
(now(), now(), 39, 0, '', 'W', 1),
(now(), now(), 39, 1, '', 'W', 0.5),
(now(), now(), 39, 2, '', 'W', 0),
(now(), now(), 39, 3, '', 'L', 0.5),
(now(), now(), 39, 4, '', 'L', 1),
(now(), now(), 40, 0, '', 'W', 1),
(now(), now(), 40, 1, '', 'W', 0.5),
(now(), now(), 40, 2, '', 'W', 0),
(now(), now(), 40, 3, '', 'L', 0.5),
(now(), now(), 40, 4, '', 'L', 1),
(now(), now(), 41, 0, '프론트엔드', 'J', 0),
(now(), now(), 41, 1, '백엔드', 'J', 0),
(now(), now(), 42, 0, '0 ~ 1년', 'Y', 0),
(now(), now(), 42, 1, '1 ~ 3년', 'Y', 0),
(now(), now(), 42, 2, '4년 이상', 'Y', 0);

INSERT INTO review (review_type, headline, title, contents) VALUES
('VSPL', '열정적인 꿈을 가진 당신은 야망가 VSPL', '당신은 VSPL', '열정적인 꿈을 가진 당신은 VSPL'),
('VSPW', '열정적인 꿈을 가진 당신은 야망가 VSPW', '당신은 VSPW', '열정적인 꿈을 가진 당신은 VSPW'),
('VSTL', '열정적인 꿈을 가진 당신은 야망가 VSTL', '당신은 VSTL', '열정적인 꿈을 가진 당신은 VSTL'),
('VSTW', '열정적인 꿈을 가진 당신은 야망가 VSTW', '당신은 VSTW', '열정적인 꿈을 가진 당신은 VSTW'),
('VCPL', '열정적인 꿈을 가진 당신은 야망가 VCPL', '당신은 VCPL', '열정적인 꿈을 가진 당신은 VCPL'),
('VCPW', '열정적인 꿈을 가진 당신은 야망가 VCPW', '당신은 VCPW', '열정적인 꿈을 가진 당신은 VCPW'),
('VCTL', '열정적인 꿈을 가진 당신은 야망가 VCTL', '당신은 VCTL', '열정적인 꿈을 가진 당신은 VCTL'),
('VCTW', '열정적인 꿈을 가진 당신은 야망가 VCTW', '당신은 VCTW', '열정적인 꿈을 가진 당신은 VCTW'),
('ASPL', '열정적인 꿈을 가진 당신은 야망가 ASPL', '당신은 ASPL', '열정적인 꿈을 가진 당신은 ASPL'),
('ASPW', '열정적인 꿈을 가진 당신은 야망가 ASPW', '당신은 ASPW', '열정적인 꿈을 가진 당신은 ASPW'),
('ASTL', '열정적인 꿈을 가진 당신은 야망가 ASTL', '당신은 ASTL', '열정적인 꿈을 가진 당신은 ASTL'),
('ASTW', '열정적인 꿈을 가진 당신은 야망가 ASTW', '당신은 ASTW', '열정적인 꿈을 가진 당신은 ASTW'),
('ACPL', '열정적인 꿈을 가진 당신은 야망가 ACPL', '당신은 ACPL', '열정적인 꿈을 가진 당신은 ACPL'),
('ACPW', '열정적인 꿈을 가진 당신은 야망가 ACPW', '당신은 ACPW', '열정적인 꿈을 가진 당신은 ACPW'),
('ACTL', '열정적인 꿈을 가진 당신은 야망가 ACTL', '당신은 ACTL', '열정적인 꿈을 가진 당신은 ACTL'),
('ACTW', '열정적인 꿈을 가진 당신은 야망가 ACTW', '당신은 ACTW', '열정적인 꿈을 가진 당신은 ACTW'),
('VF', '', '당신은 VF', '열정적인 꿈을 가진 당신은 VF'),
('VB', '', '당신은 VB', '열정적인 꿈을 가진 당신은 VB'),
('AF', '', '당신은 AF', '열정적인 꿈을 가진 당신은 AF'),
('AB', '', '당신은 AB', '열정적인 꿈을 가진 당신은 AB'),
('S1', '', '당신은 S1', '열정적인 꿈을 가진 당신은 S1'),
('S2', '', '당신은 S2', '열정적인 꿈을 가진 당신은 S2'),
('C1', '', '당신은 C1', '열정적인 꿈을 가진 당신은 C1'),
('C2', '', '당신은 C2', '열정적인 꿈을 가진 당신은 C2'),
('P', '', '당신은 P', '도전 정신이 강합니다! 무언가 확장하는 것을 좋아하는 당신, 자신의 분야 외에 다른 분야도 관심이 많습니다. 또한 새로운 서비스나 요즘 핫한 이슈를 항상 예의 주시하고 있군요. 어쩌면 당신은 핵인싸의 기질을 가지고 있을 수도 있겠군요.'),
('T', '', '당신은 T', '한 가지에 꽂히면 몰두하는 스타일입니다. 이러한 성향이 자신의 커리어을 쌓을 때도 반영이 되곤 합니다. 깊은 연구 습득 능력과 항상 호기심에 가득한 당신은 열정적인 기술 중심의 성향을 가지고 있습니다.'),
('W', '', '당신은 W', '일을 사랑하는 당신, 주어진 업무에 매사 최선을 다하고 싶어합니다. 목표설정에 따른 행동이 주체적인 사람입니다. 계획에 따라 성과가 최대치 일때 일에 대한 만족감을 얻고 능률이 오릅니다.'),
('L', '', '당신은 L', '인생에서 자신을 더 많이 사랑하는 당신! 일 할땐 일 하고 쉴땐 후회없이 푹 쉬고 싶어합니다. 쉬는 시간엔 업무 관련된 모든일은 OFF합니다. 그래야 다음 스케줄을 효과적으로 소화할 수 있습니다!');

INSERT INTO advertisement (created_at, updated_at, advertisement_ent_date, advertisement_start_date, advertisement_type, advertiser, image_url, title) VALUES
(now(), now(), now(), now(), 'LECTURE', '김상혁', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.yna.co.kr%2Fview%2FAKR20200117042400030&psig=AOvVaw27KKp3K51zckObAoDLKGxh&ust=1622812930819000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKj2s7fH-_ACFQAAAAAdAAAAABAD', '광고테스트1'),
(now(), now(), now(), now(), 'LECTURE', '김상혁', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.yna.co.kr%2Fview%2FAKR20200117042400030&psig=AOvVaw27KKp3K51zckObAoDLKGxh&ust=1622812930819000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKj2s7fH-_ACFQAAAAAdAAAAABAD', '광고테스트2'),
(now(), now(), now(), now(), 'RECRUIT', '김상혁', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.yna.co.kr%2Fview%2FAKR20200117042400030&psig=AOvVaw27KKp3K51zckObAoDLKGxh&ust=1622812930819000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKj2s7fH-_ACFQAAAAAdAAAAABAD', '광고테스트3'),
(now(), now(), now(), now(), 'RECRUIT', '김상혁', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.yna.co.kr%2Fview%2FAKR20200117042400030&psig=AOvVaw27KKp3K51zckObAoDLKGxh&ust=1622812930819000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKj2s7fH-_ACFQAAAAAdAAAAABAD', '광고테스트4');